[package]
name = "scan-statistics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vega_lite_5 = "0.7.0"
serde_json = "1.0"